### PR TITLE
Updating profiler and trace dependencies

### PR DESCRIPTION
**Pull request by kolanos**

### CODE REVIEW

**Review by mrickard — APPROVED** [review]
👍

**Comment by mrickard** [comment]
Hmmm...odd that status is taking so long on this one.  Looks like gitclear is returning a 500 on its webhook for some reason.

**Comment by kolanos** [comment]
There is no workflow for pull requests. Only a deploy job.

**Comment by mrickard** [comment]
That makes sense...though when I look at the web hooks, there are a lot of 500s from gitclear (as opposed to a 204 on June 27, the last successful gitclear call on this repo).  But that seems to be an unrelated issue, then.

**Pull request merged**
